<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addProductButton</name>
   <tag></tag>
   <elementGuidId>933f5a2c-0a79-4c62-a3fd-d50a83cf478f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//span[text()='Product']/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//span[text()='Product']/..</value>
   </webElementProperties>
</WebElementEntity>
