<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenAnyExistingProduct(productName)</name>
   <tag></tag>
   <elementGuidId>fb932adb-082a-4360-b571-6f800f8f7b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='row-30406']//div[text()='${productName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='row-30406']//div[text()='${productName}']</value>
   </webElementProperties>
</WebElementEntity>
