<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fixedAndScrollingDetect</name>
   <tag></tag>
   <elementGuidId>88fe95a3-fc1a-42e5-a54e-1ec0bc8cb2fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='endless-aisle-asset-grid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='endless-aisle-asset-grid']</value>
   </webElementProperties>
</WebElementEntity>
