<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addAssetbutton</name>
   <tag></tag>
   <elementGuidId>b1a3262f-fab2-40a2-976e-9c8a946d7703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='table-toolbar-wrapper']//button//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='table-toolbar-wrapper']//button//span</value>
   </webElementProperties>
</WebElementEntity>
