<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>journeyNameCheckBox(name)</name>
   <tag></tag>
   <elementGuidId>86ab9570-9e85-4f8d-ac57-9e81531c96d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${journeyName}']/../..//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${journeyName}']/../..//input</value>
   </webElementProperties>
</WebElementEntity>
