<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddBrandButtonInAddBrandPopup</name>
   <tag></tag>
   <elementGuidId>ef1da8eb-51e3-42d7-9b3c-7af2366e9fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='modal-footer']//button)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='modal-footer']//button)[2]</value>
   </webElementProperties>
</WebElementEntity>
