<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetCount</name>
   <tag></tag>
   <elementGuidId>44453ec1-ce9b-406e-b534-a3903de763b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'rdt_TableBody')]//div[@role=&quot;row&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'rdt_TableBody')]//div[@role=&quot;row&quot;]</value>
   </webElementProperties>
</WebElementEntity>
