<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delAssetCheckbox(assetName)</name>
   <tag></tag>
   <elementGuidId>fa51e3e1-1b3b-4818-98a2-287aecef59ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[text()=&quot;${assetName}&quot;]/../..//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()=&quot;${assetName}&quot;]/../..//div</value>
   </webElementProperties>
</WebElementEntity>
