<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>randomAsset(index)</name>
   <tag></tag>
   <elementGuidId>0d8ce0c5-1358-42d2-9ae9-c78c58ebbd3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'rdt_TableBody')]//div[@role=&quot;row&quot;][${index}]//div[@role=&quot;cell&quot;][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'rdt_TableBody')]//div[@role=&quot;row&quot;][${index}]//div[@role=&quot;cell&quot;][4]</value>
   </webElementProperties>
</WebElementEntity>
