<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>target</name>
   <tag></tag>
   <elementGuidId>c17de9ac-fa0f-4c24-95e3-237c0f5ce43f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-rbd-droppable-id=&quot;29835&quot;]//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-rbd-droppable-id=&quot;29835&quot;]//img</value>
   </webElementProperties>
</WebElementEntity>
